# Bài tập thực hành tuần 1  
> Họ và tên: Nguyễn Vạn Phúc Huy <br>
> MSSV: 23110163 <br>
> Lớp: 23TTH (Chiều thứ 6, ca 1)

Import các thư viện cần thiết

In [1]:
import numpy as np
import pandas as pd
import scipy
from sklearn.preprocessing import StandardScaler, KBinsDiscretizer
from sklearn.decomposition import PCA

### 1. Làm sạch và tiền xử lý dữ liệu:

In [2]:
df = pd.read_csv('data.csv')
df.set_index('ID', inplace=True)
df

   First Name Last Name   Age Gender Department   Salary Date of Joining
ID
1        John       Doe  25.0      M      Sales  50000.0        1/1/2020
2        Jane     Smith  30.0      F  Marketing  60000.0        6/1/2018
3         Bod   Johnson  45.0      M         HR  70000.0        9/1/2016
4       Alice  Williams  33.0      F         IT  80000.0        2/1/2017
5       James     Brown  27.0      M      Sales  55000.0        3/1/2019
6       Sarah       Lee   NaN      F  Marketing  65000.0       12/1/2018
7     Michael     Davis  39.0      M         HR      NaN        8/1/2015
8       Susan    Miller  42.0      F         IT  90000.0       11/1/2014
9       David    Wilson  28.0      M      Sales  60000.0        5/1/2020
10      Emily     Brown  35.0      F  Marketing  55000.0        4/1/2017
11       John       Doe  25.0      M      Sales  50000.0        1/1/2020
12       John       Doe  25.0      M      Sales  50000.0        1/1/2020

In [3]:
print(df.isnull().sum())

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df

First Name         0
Last Name          0
Age                1
Gender             0
Department         0
Salary             1
Date of Joining    0
dtype: int64

,First Name,Last Name,Age,Gender,Department,Salary,Date of Joining
ID,,,,,,,
1,John,Doe,25.000000,M,Sales,50000.000000,1/1/2020
2,Jane,Smith,30.000000,F,Marketing,60000.000000,6/1/2018
3,Bod,Johnson,45.000000,M,HR,70000.000000,9/1/2016
4,Alice,Williams,33.000000,F,IT,80000.000000,2/1/2017
5,James,Brown,27.000000,M,Sales,55000.000000,3/1/2019
6,Sarah,Lee,32.181818,F,Marketing,65000.000000,12/1/2018
7,Michael,Davis,39.000000,M,HR,62272.727273,8/1/2015
8,Susan,Miller,42.000000,F,IT,90000.000000,11/1/2014
9,David,Wilson,28.000000,M,Sales,60000.000000,5/1/2020
10,Emily,Brown,35.000000,F,Marketing,55000.000000,4/1/2017
11,John,Doe,25.000000,M,Sales,50000.000000,1/1/2020
12,John,Doe,25.000000,M,Sales,50000.000000,1/1/2020

In [4]:
print(df.duplicated().sum())

df = df.drop_duplicates()
df

2

,First Name,Last Name,Age,Gender,Department,Salary,Date of Joining
ID,,,,,,,
1,John,Doe,25.000000,M,Sales,50000.000000,1/1/2020
2,Jane,Smith,30.000000,F,Marketing,60000.000000,6/1/2018
3,Bod,Johnson,45.000000,M,HR,70000.000000,9/1/2016
4,Alice,Williams,33.000000,F,IT,80000.000000,2/1/2017
5,James,Brown,27.000000,M,Sales,55000.000000,3/1/2019
6,Sarah,Lee,32.181818,F,Marketing,65000.000000,12/1/2018
7,Michael,Davis,39.000000,M,HR,62272.727273,8/1/2015
8,Susan,Miller,42.000000,F,IT,90000.000000,11/1/2014
9,David,Wilson,28.000000,M,Sales,60000.000000,5/1/2020
10,Emily,Brown,35.000000,F,Marketing,55000.000000,4/1/2017

In [5]:
df = pd.get_dummies(df, columns=['Gender', 'Department'], dtype=int)
df

,First Name,Last Name,Age,Salary,Date of Joining,Gender_F,Gender_M,Department_HR,Department_IT,Department_Marketing,Department_Sales
ID,,,,,,,,,,,
1,John,Doe,25.000000,50000.000000,1/1/2020,0,1,0,0,0,1
2,Jane,Smith,30.000000,60000.000000,6/1/2018,1,0,0,0,1,0
3,Bod,Johnson,45.000000,70000.000000,9/1/2016,0,1,1,0,0,0
4,Alice,Williams,33.000000,80000.000000,2/1/2017,1,0,0,1,0,0
5,James,Brown,27.000000,55000.000000,3/1/2019,0,1,0,0,0,1
6,Sarah,Lee,32.181818,65000.000000,12/1/2018,1,0,0,0,1,0
7,Michael,Davis,39.000000,62272.727273,8/1/2015,0,1,1,0,0,0
8,Susan,Miller,42.000000,90000.000000,11/1/2014,1,0,0,1,0,0
9,David,Wilson,28.000000,60000.000000,5/1/2020,0,1,0,0,0,1
10,Emily,Brown,35.000000,55000.000000,4/1/2017,1,0,0,0,1,0